services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=internet_metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_USER=internetmon
      - INFLUXDB_USER_PASSWORD=password123
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    restart: unless-stopped

  internet-monitor:
    build:
      context: .
    container_name: internet-monitor
    depends_on:
      - influxdb
    environment:
      - RUST_LOG=info
    command: >
      --interval 5
      --influxdb-url http://influxdb:8086
      --influxdb-db internet_metrics
      --influxdb-username internetmon
      --influxdb-password password123
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data: